---
  name: Java CI
  on:
    - push
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: "17"
            distribution: temurin
        - name: Build
          run: mvn --batch-mode --update-snapshots package
        - name: Copy Jar file
          run: mv target/*.jar app.jar
        - uses: actions/upload-artifact@master
          with:
            name: jar-file
            path: app.jar

            
      jobs:
        build-image:
          runs-on: ubuntu-latest
          needs: build
          steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@master
              with:
                name: jar-file
                path: app.jar
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Set env
              run: echo "DATE=$(date +%s)" >> $GITHUB_ENV
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                context: .
                push: true
                tags: thearaseng/dockerized-spring-boot-app:${{ env.DATE }}
  