name: Deploy to Minikube usando Github Actions
on: push  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: RUN deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Deploy to minikube
      run: |
        kubectl create ns prod
        kubectl apply -f deployment.yaml -n prod
    - name: Teste pods
      run: |
        kubectl get pods -n prod
