---
  name: Java CI
  on:
    - push
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: "17"
            distribution: temurin
        - name: Build
          run: mvn --batch-mode --update-snapshots package
        - name: Copy Jar file
          run: |
          mkdir /work/application.jar
          mv target/*.jar /work/application.jar
        - uses: actions/upload-artifact@master
          with:
            name: jar-file
            path: application.jar